#定义后台管理consumer启动器端口为8001
server:
  port: 8001
  
#定义jsp相关
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/ 
      suffix: .jsp
#激活common中的配置文件
  profiles:
    active: picEnv
  #非要带上老四条才能运行我是没想到的
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ego?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: a123456
#定义dubbo consumer配置
dubbo:
  application:
    name: zuel-manage-consumer
  registry:
    id: ManagerConsumer
    address: zookeeper://192.168.10.10:2181
  protocol:
    port: 20882
    name: dubbo  
    

