server:
  port: 8002
  
spring:
  rabbitmq:
    host: 192.168.10.11
    port: 5672
    username: root
    password: a123456
    virtual-host: / 
  profiles:
    active: content,redis
    
zuel:
  message:
    content:
      sync:
        exchange: zuel_content_sync_ex
        routingKey: content_rk
        queueName: zuel_content_sync_queue
        
dubbo:
  application:
    name: zuel_message_consumer
  registry:
    address: zookeeper://192.168.10.10:2181