server:
  port: 8085
spring:
  profiles:
    active: redis,itemCache,cart
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
dubbo:
  application:
    name: zuel_front_cart
  registry:
    address: zookeeper://192.168.10.10:2181