#换一个端口
server:
  port: 8000

#配置dubbo名称以及zookeeper
dubbo:
  application:
    name: zuel-provider-manage
  registry:
    id: ManagerProvider
    address: zookeeper://192.168.10.10:2181
  protocol:
    port: 20881
    name: dubbo
#  scan:
#   base-packages:
#    - zuel-api-manage

#启用dao中的配置文件
spring:
  profiles:
    active:
    - db
    
